# Generated by Django 2.2.1 on 2019-10-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190924_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.TextField(default='No background added yet. Give your character a background using the link below!'),
            preserve_default=False,
        ),
    ]
