# Generated by Django 2.2.1 on 2019-10-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='char_class',
            field=models.CharField(default='Fighter', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.TextField(default='No background created yet.'),
        ),
    ]
