# Generated by Django 2.2.1 on 2019-10-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191008_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='char_class',
        ),
        migrations.AddField(
            model_name='profile',
            name='charClass',
            field=models.CharField(choices=[('barbarian', 'BARBARIAN'), ('bard', 'BARD'), ('cleric', 'CLERIC')], default='', max_length=10),
        ),
    ]
