# Generated by Django 2.2.1 on 2019-10-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191008_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='race',
            field=models.CharField(choices=[('dragonborn', 'DRAGONBORN'), ('dwarf', 'DWARF'), ('elf', 'ELF'), ('gnome', 'GNOME'), ('half-elf', 'HALF-ELF'), ('halfling', 'HALFLING'), ('half-orc', 'HALF-ORC'), ('human', 'HUMAN'), ('tiefling', 'TIEFLING')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='charClass',
            field=models.CharField(choices=[('barbarian', 'BARBARIAN'), ('bard', 'BARD'), ('cleric', 'CLERIC'), ('druid', 'DRUID'), ('fighter', 'FIGHTER'), ('monk', 'MONK'), ('paladin', 'PALADIN'), ('ranger', 'RANGER'), ('rogue', 'ROGUE'), ('sorcerer', 'SORCERER'), ('warlock', 'WARLOCK'), ('wizard', 'WIZARD')], default='', max_length=10),
        ),
    ]
