# Generated by Django 2.2.1 on 2019-10-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191008_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='charClass',
            field=models.CharField(choices=[('', ''), ('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Fighter', 'Fighter'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.CharField(choices=[('', ''), ('Dragonborn', 'Dragonborn'), ('Dwarf', 'Dwarf'), ('Elf', 'Elf'), ('Gnome', 'Gnome'), ('Half-elf', 'Half-Elf'), ('Halfling', 'Halfling'), ('Half-orc', 'Half-Orc'), ('Human', 'Human'), ('Tabaxi', 'Tabaxi'), ('Tiefling', 'Tiefling')], default='', max_length=15),
        ),
    ]
