# Generated by Django 2.2.1 on 2019-09-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltmarsh', '0003_auto_20190924_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='welcome-to-saltmarsh'),
            preserve_default=False,
        ),
    ]
